version: "3.5"
# docker run -p 3000:3000 \   
#     -v ~/dev/temp/metabase-data/mtdata:/metabase-data \
#     -e "MB_DB_FILE=./metabase-data/metabase.db" \
#     --name metabase metabase/metabase

services: 
  metabase: 
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    environment: 
      MB_DB_FILE: ./metabase-data/metabase.db
    volumes:
      - ${PWD}/local/metabase-data/mtdata:/metabase-data